#!/usr/bin/env python3
"""App symbols for LiDio and LiDio privat, the same on the desktop, the phone and the homepage (card 0fc6d317, Olaf 06.10.2026:
"ähnlich hell wie vom Kalender und mit Farbverlauf in der Note … am Desktop und Handy einheitlich"): a light face (white → light
grey, like LiCal's), the two beamed notes in a colour gradient – coral → violet for LiDio, teal → indigo for LiDio privat.
  python3 tools/make_icons.py      (writes the files listed in OUT; run from the repo root)"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VARIANTS = {"oeffentlich": ("#FF4F6D", "#7B3FE4"), "privat": ("#1FC8B4", "#3A3FD9")}
# The notes (viewport 108, inside Android's 66 dp safe zone) – same drawing as before, a little bolder.
NOTES = ('<g transform="translate(54 54) scale(1.12) translate(-54 -53)">'
         '<ellipse cx="39" cy="71" rx="9.4" ry="6.8" transform="rotate(-20 39 71)"/>'
         '<ellipse cx="64" cy="65" rx="9.4" ry="6.8" transform="rotate(-20 64 65)"/>'
         '<path d="M44.2,37 L49.2,37 L49.2,71 L44.2,71 Z"/><path d="M69.2,31 L74.2,31 L74.2,65 L69.2,65 Z"/>'
         '<path d="M44.2,37 L74.2,28.6 L74.2,38.6 L44.2,47 Z"/></g>')


def svg(top, bottom):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 108 108">
  <!-- Generated by tools/make_icons.py – a light face like LiCal's, the notes in a colour gradient. -->
  <defs>
    <linearGradient id="face" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#FFFFFF"/><stop offset="1" stop-color="#ECECEF"/></linearGradient>
    <linearGradient id="note" x1="0.15" y1="0" x2="0.85" y2="1"><stop offset="0" stop-color="{top}"/><stop offset="1" stop-color="{bottom}"/></linearGradient>
    <filter id="shadow" x="-10%" y="-10%" width="120%" height="125%"><feDropShadow dx="0" dy="1.1" stdDeviation="1.7" flood-color="#000" flood-opacity="0.22"/></filter>
  </defs>
  <rect x="8" y="8" width="92" height="92" rx="21" fill="url(#face)" filter="url(#shadow)"/>
  <g fill="url(#note)">{NOTES}</g>
</svg>
'''


def foreground(top, bottom):
    def path(d, rot=None):
        grad = (f'<aapt:attr name="android:fillColor"><gradient android:type="linear" android:startX="44" android:startY="28" '
                f'android:endX="74" android:endY="80"><item android:offset="0" android:color="#FF{top[1:]}"/>'
                f'<item android:offset="1" android:color="#FF{bottom[1:]}"/></gradient></aapt:attr>')
        p = f'<path android:pathData="{d}">{grad}</path>'
        return f'<group android:rotation="-20" android:pivotX="{rot[0]}" android:pivotY="{rot[1]}">{p}</group>' if rot else p
    parts = [path("M29.6,71 A9.4,6.8 0 1,0 48.4,71 A9.4,6.8 0 1,0 29.6,71 Z", (39, 71)),
             path("M54.6,65 A9.4,6.8 0 1,0 73.4,65 A9.4,6.8 0 1,0 54.6,65 Z", (64, 65)),
             path("M44.2,37 L49.2,37 L49.2,71 L44.2,71 Z"), path("M69.2,31 L74.2,31 L74.2,65 L69.2,65 Z"),
             path("M44.2,37 L74.2,28.6 L74.2,38.6 L44.2,47 Z")]
    return ('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/make_icons.py (card 0fc6d317): the notes in a colour gradient. -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt"\n'
            '    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">\n'
            '    <group android:translateX="54" android:translateY="54" android:scaleX="1.12" android:scaleY="1.12">\n'
            '    <group android:translateX="-54" android:translateY="-53">\n        ' + "\n        ".join(parts) +
            '\n    </group>\n    </group>\n</vector>\n')


BACKGROUND = ('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/make_icons.py (card 0fc6d317): a light face like LiCal\'s. -->\n'
              '<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">\n'
              '    <gradient android:startColor="#FFFFFFFF" android:endColor="#FFECECEF" android:angle="270" />\n</shape>\n')

OUT = {
    "linux/data/io.github.veritasx1.LiDio.svg": svg(*VARIANTS["oeffentlich"]),
    "homepage/lidio.svg": svg(*VARIANTS["oeffentlich"]),
    "android/app/src/main/res/drawable/ic_launcher_background.xml": BACKGROUND,
    "android/app/src/main/res/drawable/ic_launcher_foreground.xml": foreground(*VARIANTS["oeffentlich"]),
}
if os.path.isdir(os.path.join(ROOT, "android/app/src/privat")):
    OUT["linux/data/io.github.veritasx1.LiDio" + ".Privat.svg"] = svg(*VARIANTS["privat"])
    OUT["android/app/src/privat/res/drawable/ic_launcher_background.xml"] = BACKGROUND
    OUT["android/app/src/privat/res/drawable/ic_launcher_foreground.xml"] = foreground(*VARIANTS["privat"])

for rel, text in OUT.items():
    with open(os.path.join(ROOT, rel), "w") as f:
        f.write(text)
    print("geschrieben:", rel)
